# Generated by Django 3.2.7 on 2021-09-11 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('time', models.DateTimeField(verbose_name='set finish time')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_workout.workout')),
            ],
        ),
    ]
