# Generated by Django 3.2.7 on 2021-09-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_workout', '0003_exerciseset_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseset',
            name='time',
        ),
    ]
