# Generated by Django 3.2.7 on 2021-09-11 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_workout', '0006_auto_20210911_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 20, 50, 16, 330693)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(verbose_name='pub date'),
        ),
    ]
