# Generated by Django 3.2.7 on 2021-09-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_workout', '0007_auto_20210911_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
