# Generated by Django 3.2.7 on 2021-09-11 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_workout', '0008_alter_exerciseset_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 21, 26, 47, 755997)),
        ),
    ]
