# Generated by Django 3.2.7 on 2021-09-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_workout', '0009_alter_exerciseset_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
