# Generated by Django 3.2.7 on 2021-09-12 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_workout', '0010_alter_exerciseset_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 19, 9, 43, 121252)),
        ),
    ]
